server:
  port: 8083
spring:
  application:
    name: flyway-migration-example
  datasource:
    driverClassName: com.mysql.cj.jdbc.Driver
    password: ABCD@XYZ
    url: jdbc:mysql://localhost:3306/schema_name
    username: userName
  flyway:
    enabled: true
    locations: classpath:db/migration
    password: ABCD@XYZ
    schemas: schema_name
    user: userName
  jpa:
    generate-ddl: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL55Dialect
    show-sql: true